defaults: &default_steps
  docker:
    - image: docker:stable
  steps:
    - setup_remote_docker:
        version: 18.05.0-ce
    - checkout
    - run: apk add --no-cache make git curl
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: '[ -n "$REGISTER" ] && make register || true' 
    - run: make $CIRCLE_JOB


version: 2
jobs:
  alpine-x86_64:
    <<: *default_steps

  alpine-arm64v8:
    <<: *default_steps
    environment:
      REGISTER: register

  ubuntu-x86_64:
    <<: *default_steps

  ubuntu-arm64v8:
    <<: *default_steps
    environment:
      REGISTER: register

workflows:
  version: 2
  build:
    jobs:
      - alpine-x86_64
      - alpine-arm64v8
      - ubuntu-x86_64
      - ubuntu-arm64v8

