version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - checkout
      - run:
          name: Wrap with qemu the arm32v7/ubuntu:bionic 
          command: |
            # Steal (sorry) qemu from altlinux
            apk add --no-cache rpm
            cd qemu-wrapper
            wget https://github.com/multiarch/qemu-user-static/releases/download/v2.12.0/qemu-arm-static.tar.gz
            tar xzf qemu-arm-static.tar.gz
            # Override the tagged image with the new one
            docker build -t arm32v7/ubuntu:bionic .
            cd ..
      - run:
          name: Register binfmt
          command: docker run --rm --privileged multiarch/qemu-user-static:register -c yes
      - run:
          name: Build the docker image
          command: |
            docker build -t graffic/elixir-ubuntu-armv7:latest .
      - run:
          name: Push to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push graffic/elixir-ubuntu-armv7:latest
